import image from "./images/004.jpg";

export default {
    alias: 'alias-service-004',
    image: image,
    name: "Еще одна услуга",
    description: "Nulla malesuada, tortor vitae tempus bibendum, erat erat volutpat orci, at viverra ipsum leo quis odio. Vivamus eleifend mauris id ligula luctus euismod. Maecenas tempor, magna vel ornare molestie, lorem mi tempus magna, vitae posuere sem magna eget quam. Ut id libero sapien. Vestibulum quis turpis malesuada nisi auctor finibus. Sed quis ligula ut odio ultricies fermentum. Sed in justo scelerisque, volutpat lacus ac, blandit magna. Aliquam finibus nisi nisi, in mattis odio malesuada ut. Maecenas vulputate dolor et quam tincidunt tempus. Pellentesque finibus sem ante, non tristique enim tempor sed. Donec tempor consectetur lacus, non sollicitudin sem egestas et." +
        "<p>Maecenas ante dolor, varius nec odio eu, interdum rhoncus dui. Nulla a augue in neque aliquet euismod vitae in velit. Sed quis consectetur ante, vel laoreet justo. Cras vel ex hendrerit, hendrerit justo ac, iaculis ex. Duis malesuada pulvinar blandit. Aliquam et tortor risus. Nullam pretium ultrices neque in finibus. Morbi nec ipsum eros. Proin suscipit tempor congue. Vivamus eget lorem augue. Aliquam erat volutpat. Etiam ut elit quam. Fusce ut tortor dapibus, mollis urna vitae, semper diam. Proin sollicitudin erat tellus, sed hendrerit neque gravida eget. Etiam sit amet porta risus. Integer tempor lorem vel nunc vulputate tempus.</p>" +
        "<p>Integer faucibus diam at dui sollicitudin, quis imperdiet nunc ultrices. Nunc rhoncus venenatis lacus, at semper augue posuere quis. Ut eu nisl risus. Nullam ac purus aliquet mauris commodo dictum a vitae nibh. Duis tempus lorem eu justo tempor ornare. Donec venenatis, turpis nec accumsan fermentum, enim augue interdum quam, eget sagittis lacus tellus eu magna. Pellentesque consectetur eget arcu sed mollis. Proin ut commodo odio, eu ultrices erat. Mauris commodo orci facilisis ex malesuada, vel interdum urna semper. Donec at massa odio. Nullam vel eleifend arcu. Nam mi tortor, interdum id nisl nec, porta molestie mi.</p>" +
        "<p>Maecenas ante dolor, varius nec odio eu, interdum rhoncus dui. Nulla a augue in neque aliquet euismod vitae in velit. Sed quis consectetur ante, vel laoreet justo. Cras vel ex hendrerit, hendrerit justo ac, iaculis ex. Duis malesuada pulvinar blandit. Aliquam et tortor risus. Nullam pretium ultrices neque in finibus. Morbi nec ipsum eros. Proin suscipit tempor congue. Vivamus eget lorem augue. Aliquam erat volutpat. Etiam ut elit quam. Fusce ut tortor dapibus, mollis urna vitae, semper diam. Proin sollicitudin erat tellus, sed hendrerit neque gravida eget. Etiam sit amet porta risus. Integer tempor lorem vel nunc vulputate tempus.</p>" +
        "<p>Integer faucibus diam at dui sollicitudin, quis imperdiet nunc ultrices. Nunc rhoncus venenatis lacus, at semper augue posuere quis. Ut eu nisl risus. Nullam ac purus aliquet mauris commodo dictum a vitae nibh. Duis tempus lorem eu justo tempor ornare. Donec venenatis, turpis nec accumsan fermentum, enim augue interdum quam, eget sagittis lacus tellus eu magna. Pellentesque consectetur eget arcu sed mollis. Proin ut commodo odio, eu ultrices erat. Mauris commodo orci facilisis ex malesuada, vel interdum urna semper. Donec at massa odio. Nullam vel eleifend arcu. Nam mi tortor, interdum id nisl nec, porta molestie mi.</p>" +
        "<p>Phasellus porttitor id diam et posuere. Mauris interdum non lectus eget accumsan. Vivamus sed purus vitae massa fermentum euismod semper sed tellus. Fusce sollicitudin metus eget dolor rhoncus facilisis et in lorem. Aenean aliquet erat id massa aliquam dignissim sed at tortor. Nunc eu ipsum eros. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque gravida ultrices condimentum. Donec in neque rhoncus dolor porta tristique sit amet at leo. Praesent a turpis a eros mollis viverra. Sed et nisl ac mi congue porttitor. Aenean sapien metus, accumsan id lorem sit amet, fermentum mattis nibh. Donec ut mattis sapien, ut tempor quam. Vivamus vel urna vitae tellus laoreet fermentum. Sed eu faucibus quam. Fusce ac ornare quam.</p>" +
        "<p>Nulla malesuada, tortor vitae tempus bibendum, erat erat volutpat orci, at viverra ipsum leo quis odio. Vivamus eleifend mauris id ligula luctus euismod. Maecenas tempor, magna vel ornare molestie, lorem mi tempus magna, vitae posuere sem magna eget quam. Ut id libero sapien. Vestibulum quis turpis malesuada nisi auctor finibus. Sed quis ligula ut odio ultricies fermentum. Sed in justo scelerisque, volutpat lacus ac, blandit magna. Aliquam finibus nisi nisi, in mattis odio malesuada ut. Maecenas vulputate dolor et quam tincidunt tempus. Pellentesque finibus sem ante, non tristique enim tempor sed. Donec tempor consectetur lacus, non sollicitudin sem egestas et.</p>"
}